### ISSUE TITLE
example-dapp: Write a tutorial using this repo

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-example-dapp#3]
Write up a tutorial using this repo.

Tutorial should include:
- Clone the repo
- Set up and run it locally
- Tweak the contract
- Tweak the app
- Deploy id

**Comment by leighmcculloch** [comment]
If this tutorial is to capture this example, I'd add an example page instead of a tutorial page. I think when we discussed this previously I might have said tutorial but I meant example.

And then for a tutorial having a tutorial that demonstrates how to run the rpc server, and a super super basic use of the frontend SDK to invoke the contract. To go with the other tutorials here: https://soroban.stellar.org/docs/category/tutorials
