### ISSUE TITLE
Unable to complete ./initialize.sh

### ISSUE THREAD

**Issue by amissine** [stellar/soroban-example-dapp#45]
### What version are you using?

Searched `package-lock.json` for `stellar`:
```
    "@stellar/freighter-api": {
      "version": "1.3.1",
...
    "stellar-base": {
      "version": "8.0.1-soroban.3",
...
```
### What did you do?

Ran `./initialize.sh`

### What did you expect to see?
Successful completeness

### What did you see instead?
```
...
    Finished release [optimized] target(s) in 1m 55s
CARGO_TARGET_DIR=target-tiny cargo +nightly build --target wasm32-unknown-unknown --release \
  -Z build-std=std,panic_abort \
  -Z build-std-features=panic_immediate_abort
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
make: *** [Makefile:10: build] Error 1
```

**Comment by amissine** [comment]
Line split did not help:
```
CARGO_TARGET_DIR=target-tiny 
cargo +nightly build --target wasm32-unknown-unknown --release \
	-Z build-std=std,panic_abort \
	-Z build-std-features=panic_immediate_abort
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
make: *** [Makefile:11: build] Error 1
```

**Comment by leighmcculloch** [comment]
@amissine You'll need to install the nightly Rust toolchain and some additional tools. For instructions for how to install those tools, see: https://soroban.stellar.org/docs/tutorials/build-optimized.

@paulbellamy @tsachiherman We should remove the optimized build steps from this example's main build process, and have it as an added optional thing. We have kept those steps out of our other examples because they're not really required and they add significant friction to a first build experience.

**Comment by amissine** [comment]
Many thanks!

:)

**Comment by leighmcculloch** [comment]
I've opened a follow up issue to address removing the optimized build as a required step in using this example: https://github.com/stellar/soroban-example-dapp/issues/47
